### PR TITLE
allow for env var subtitution for oc exec config

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-plugin/issues/135

@bparees @oatmealraisin ptal

### CODE REVIEW

**Comment by bparees** [comment]
does this allow for parameter references or just env references?

**Comment by gabemontero** [comment]
allows for both

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
hmmm ... the extended test for freestyleexec failed (though dsl passed)

will run locally and debug

**Comment by gabemontero** [comment]
Fancy new iterator logic needs null checking:

```
Starting "OpenShift Exec" with project "extended-test-jenkins-plugin-g6bj4-3hk2n".
java.lang.NullPointerException
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftExec.getArguments(IOpenShiftExec.java:49)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftExec.coreLogic(IOpenShiftExec.java:67)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:308)
	at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:326)
	at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
ERROR: "OpenShift Exec" failed
Finished: FAILURE
```

**Pull request merged**
