### PR TITLE
change to trigger deployment via instantiate endpoint if available

### PR DESCRIPTION
**Pull request by gabemontero**
@jupierce @csrwng PTAL

stems from bugzilla 1383804

### CODE REVIEW

**Comment by gabemontero** [comment]
looks like we hit a nexus caching issue with the requisite restclient changes

will monitor that in parallel to responding to code review comments

**Comment by gabemontero** [comment]
[test]

**Comment by csrwng** [comment]
LGTM

**Comment by gabemontero** [comment]
thx @csrwng - unfortunately, the restclient version pushed to nexus today still is not showing up in the ami builds, though it is showing when I run maven locally.

I'll have to sort this out before merging.

**Comment by gabemontero** [comment]
well, I cleared out my maven .m2 cache for the restclient and now I'm seeing it locally as well.

@jcantrill - our builds our pulling versions of the rest client like:

```
 http://repository.jboss.org/nexus/content/groups/public/com/openshift/openshift-restclient-java/5.2.0-SNAPSHOT/openshift-restclient-java-5.2.0-20161013.193442-9.jar
```

which doesn't contain the updates for the deploy via instantiate endpoint.  Do we just have to be patient, or is there something else needed to get that change out there?  thanks

**Comment by jcantrill** [comment]
@gabemontero i will republish.  Maybe I did not pull before building.  I do not believe there is any sync issues....

**Comment by gabemontero** [comment]
thx @jcantrill the pull from the jboss nexus now has the updates when I try locally ... i've repushed to trigger our test jobs

**Pull request merged**
