### PR TITLE
Close race condition on log follow

### LINKED ISSUE #74: Following build logs creates 1 socket/second & duplicate log data
If you create a start-build step & specify that build logs should be streamed, you will see in the Jenkins console that each build log message is appended to the console log multiple times. 

In IOpenShiftBuilder.java, you can see why:

```
        while (System.currentTimeMillis() < (startTime + wait)) {
            bld = client.get(ResourceKind.BUILD, bldId, getNamespace(overrides));
            bldState = bld.getStatus();
            if (Boolean.parseBoolean(getVerbose(overrides)))
                listener.getLogger().println("\nOpenShiftBuilder bld state:  " + bldState);

            if (follow) {
                final String container = pod.getContainers().iterator().next().getName();
                listener.getLogger().println("CONATINERNAME: " + container);

                stop = pod.accept(new CapabilityVisitor<IPodLogRetrievalAsync, IStoppable>() {
```

Each second, a new pod.accept is being invoked (which creates a net new socket/listener for the life of the build process). 

The simple fix is to move the `if (follow){...}` block outside of the loop. However, invoking .accept too early results in an exception which is currently swallowed by the restclient. 

```
Oct 05, 2016 6:12:57 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (OkHttp Dispatcher/95) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
com.openshift.restclient.BadRequestException: https://10.13.137.145:8443/api/v1/namespaces/myproject/pods/ruby-hello-world-8-build/log?container=docker-build&follow=true container "docker-build" in pod "ruby-hello-world-8-build" is waiting to start: ContainerCreating
    at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:97)
    at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:59)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.access$100(RealCall.java:33)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

In other words, there is presently no (straightforward) way to know whether the operation fails & needs to be retried. 

Fixing it might require a slight API break in the openshift-restclient, so I've opened a PR to debate the discuss the change: openshift/openshift-restclient-java#224

### PR DESCRIPTION
**Pull request by jupierce**
Fixes #74

### CODE REVIEW

**Comment by gabemontero** [comment]
need to rebase, but pending that, and successfuly test job completion, IGTM.

**Comment by jupierce** [comment]
@gabemontero Rebase complete. fwiw, exec feature PR testing will fail until this merges because to the restclient API change.

**Comment by gabemontero** [comment]
Yep, understood on the restclient dependency.  We'll just hold tight until Jeff and team push things through.

**Comment by jupierce** [comment]
@gabemontero He has pushed. Might want to go ahead and merge.

**Comment by gabemontero** [comment]
[test]

**Pull request merged**
