### PR TITLE
switch to service.spec.clusterIP, as portalIP has been removed

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-plugin/issues/122

service.spec.portalIP was removed somewhat recently in https://github.com/openshift/origin

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
thanks @bparees - @jcantrill offered to cut an official/"final" release of the restclient for this, which is cleaner vs. using SNAPSHOT releases when cutting the official release of the plugin on jenkinsci.  Once Jeff has a chance to do that, I'll merge this.

**Comment by gabemontero** [comment]
The cutting of `5.4.0.Final` of openshift-restclient-java on the jboss nexus repo apparently hit a openshift push image to docker registry network timeout :-) (https://issues.jboss.org/browse/JBIDE-23771 and https://github.com/openshift/origin/issues/12603) 

As such, I can't cite `5.4.0.Final` as a maven dependency.  We'll hold out a bit and see if they can get this resolved before falling back on using `5.4.0-SNAPSHOT` (or possibly getting them to try a `5.5.0.Final`).  We've used their SNAPSHOT's before, so have some amount of confidence in it.

I've pushed updates that currently uses `5.4.0-SNAPSHOT`.

**Comment by gabemontero** [comment]
The latest PR test passed, but there was some vagrant / aws / ci.openshift hiccup after the extended test ran.

Also, based on how the referenced issues have progressed today, it looks like the cutting of the `5.4.0.Final` release for openshift-restclient-java might take a bit.  Going ahead with running off of SNAPSHOT, merging this, and tracking that separately.

**Pull request merged**
