### PR TITLE
disable travis

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan 
/assign @akram

### CODE REVIEW

**Comment by gabemontero** [comment]
@adambkaplan do you have the green button for this repo?  I no longer do.

if the old ci/openshift-jenkins does not pass, and if an lgtm does not work (this repo is not integrated with our prow stuff ... curious if the aos-cd-jobs stuff still works) then we may need someone like @bparees to green button this one

**Comment by adambkaplan** [comment]
> (this repo is not integrated with our prow stuff ... curious if the aos-cd-jobs stuff still works)

@gabemontero correct me if I'm wrong, https://github.com/openshift/release/pull/21474 aims to fix this situation.

**Comment by gabemontero** [comment]
> > (this repo is not integrated with our prow stuff ... curious if the aos-cd-jobs stuff still works)
> 
> @gabemontero correct me if I'm wrong, [openshift/release#21474](https://github.com/openshift/release/pull/21474) aims to fix this situation.

no they are unrelated @adambkaplan 

this repo is the old plugin that is only supported in 3.x

**Comment by gabemontero** [comment]
and yeah the old jenkins based CI is totally a no -go

/assign @bparees 

(hoping you can green button this travis disablement PR)

**Comment by gabemontero** [comment]
> and yeah the old jenkins based CI is totally a no -go
> 
> /assign @bparees
> 
> (hoping you can green button this travis disablement PR)

thanks @bparees :-)

**Pull request merged**
