### PR TITLE
release 1.0.57

### PR DESCRIPTION
**Pull request by akram**

### CODE REVIEW

**Comment by akram** [comment]
it seems we have some flakes for this one now.

errors seem to be different accross launches.

**Comment by gabemontero** [comment]
This has been failing for a while @akram 

Going to /hold

Please take a look at the logs and see if you can decipher what is going on.

**Comment by akram** [comment]
the failures really looked as flakes of the ocp cluster with timeouts while trying to access the openshift API :
```
Mar 24 18:17:51.024: INFO: Unable to retrieve pods for deploymentconfig "jenkins": Get https://ip-172-18-15-158.ec2.internal:8443/api/v1/namespaces/e2e-test-jenkins-plugin-f8p7n/pods?labelSelector=deploymentconfig%3Djenkins: dial tcp 172.18.15.158:8443: connect: connection refused

Mar 24 18:17:51.024: INFO: Logs were not captured!
<nil>
<nil>
<nil>

[AfterEach] [Feature:Builds][Slow] openshift pipeline plugin
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:77
STEP: Collecting events from namespace "e2e-test-jenkins-plugin-f8p7n".
[AfterEach] [Feature:Builds][Slow] openshift pipeline plugin
  /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:142
STEP: Dumping a list of prepulled images on each node to file /data/src/github.com/openshift/origin/_output/scripts/core/artifacts/junit/image-puller.txt
Mar 24 18:17:51.032: INFO: Error getting pods in namespace "kube-system": Get https://ip-172-18-15-158.ec2.internal:8443/api/v1/namespaces/kube-system/pods?labelSelector=name%3De2e-image-puller: dial tcp 172.18.15.158:8443: connect: connection refused
Mar 24 18:17:51.032: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
Mar 24 18:17:51.040: INFO: All nodes should be ready after test, Get https://ip-172-18-15-158.ec2.internal:8443/api/v1/nodes: dial tcp 172.18.15.158:8443: connect: connection refused

```

**Pull request merged**
