### PR TITLE
OpenShiftCreator assumes /oapi/v1 endpoints

### PR DESCRIPTION
**Pull request by warmi01**
Use Kubernetes API (/api/v1/) path for "services" requests (see open issue #2)

### CODE REVIEW

**Comment by gabemontero** [comment]
First - thanks for taking the initiative and looking to fix this.

Now, there is in fact a larger list than just services that falls under the "api" umbrella vs. "oapi" umbrella.  I'd rather address all the possibilities at once vs. just the one (i.e. services).

If you think you have the bandwidth to gather that list and update the PR, great.

If not, hopefully I'm going to dive into that research soon, but I've uncovered some other needed fixes based on recent master/slave testing that I need to sort out first.

If that keeps me occupied for too long, I'll reconsider merging in this subset fix in the interim.

thanks again

**Comment by warmi01** [comment]
Re: "Now, there is in fact a larger list than just services that falls under the "api" umbrella vs. "oapi" umbrella. I'd rather address all the possibilities at once vs. just the one (i.e. services)."

Yup, that did occur to me (define mappings for all). I just figured for the sake of simplicity/clarity I would just target the offending case I ran into and report it to you, not knowing whether there were other considerations I wasn't aware of (e.g. new planned endpoints, REST API merge plans, etc).

Sure. I can take a crack at creating a more comprehensive fix.

Thanks for the quick turnaround.

**Comment by gabemontero** [comment]
Cool deal - thx @warmi01 .  As a possible helpful pointer, I've heard (though have not confirmed with them directly) that the UI team may maintain a straight forward list of which API objects fall under api vs. oapi.  If so, perhaps @jwforres or @spadgett can confirm / elaborate.

**Comment by spadgett** [comment]
@gabemontero @warmi01 You can see the list the web console uses here:

https://github.com/openshift/origin/blob/master/assets/app/config.js

**Comment by gabemontero** [comment]
thanks @spadgett

**Comment by warmi01** [comment]
thanks @spadgett

**Comment by warmi01** [comment]
@spadgett -- so what we are actually looking for in this case are the subset of endpoints within the "namespaces" set of APIs, for example: /oapi/v1/namespaces/{namespace}/buildconfigs, /oapi/v1/namespaces/{namespace}/builds, ...), which is a somewhat lower level reduced set.

The lists you provided are 1st tier peer API endpoints with "/namespaces."

**Comment by spadgett** [comment]
@warmi01 You might look at the swagger JSON to see which `oapi` resources fall under `/namespaces`, although unfortunately it's hard to read since it's raw JSON.

https://github.com/openshift/origin/blob/master/api/swagger-spec/oapi-v1.json

**Comment by warmi01** [comment]
@spadgett Ah, yes. That works - helpful.

Thanks!

**Pull request closed without merging**
