### PR TITLE
fix sorting based on build id; incorporate start time wrt finding lat…

### LINKED ISSUE #153: Issue with Jenkin's Verify Build OpenShift plug-in functionality
We are having a recurring issue with Build Verify OpenShift functionality.  The Jenkins job is able to successfully kick off the OSE builds, but for some reason it tracks the incorrect build job instead of the latest one.  Therefore, even though the build job succeeds, the Jenkins job fails because it is waiting for the wrong job to succeed.

We were able to confirmed that there is a bug with the OSE plugin.  It is around how it sorts the list of builds.  It does it alphabetically instead of timestamp.  Therefore, for example, it places build-4 before build-38.

### PR DESCRIPTION
**Pull request by gabemontero**
…est build

fixes https://github.com/openshift/jenkins-plugin/issues/153

@openshift/devex fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
jenkins recycled during the tests ... broke a couple of in-flight activities

running tests locally now ... if pass, merging manually

**Comment by gabemontero** [comment]
jenkins recycle <== recent ci.openshift env pain

**Comment by bparees** [comment]
> running tests locally now ... if pass, merging manually

why does it need to be merged manually?

**Comment by bparees** [comment]
this doesn't seem urgent enough to justify bypassing our test/merge process.

**Comment by gabemontero** [comment]
rosie is going to complain if I don't cite a flake ... and it has to be a flake from this repo

**Comment by bparees** [comment]
just delete the rosie comments.

**Comment by gabemontero** [comment]
ok (delete comment)

**Comment by gabemontero** [comment]
fyi ... tests did pass locally for me

**Comment by bparees** [comment]
```
Using project "default".
unexpected top level element in /data/src/github.com/openshift/origin/_output/scripts/core/artifacts/build-job-clone.xml: flow-definition
[ERROR] PID 41423: test/extended/setup.sh:251: `"$( os::util::find::built_binary junitmerge )" "${TEST_REPORT_DIR}"/*.xml > "${output}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/extended/setup.sh:251: `"$( os::util::find::built_binary junitmerge )" "${TEST_REPORT_DIR}"/*.xml > "${output}"`
[INFO] 		  2: test/extended/setup.sh:26: os::test::extended::merge_junit
[INFO] 		  3: test/extended/core.sh:9: os::test::extended::focus
```

we need to get to the bottom of that.  according to @stevekuznetsov we're including files that are not junit output and should not be merged, in the junit merge operation.

**Comment by bparees** [comment]
removing junitmerge here:
https://github.com/openshift/origin/pull/16068

**Comment by gabemontero** [comment]
Thanks for the investigation/insight @bparees 

Given this fix is still low priority (though I ultimately want to get it in 3.7), I'll defer on hitting the merge button, and try the tag again when appropriate.

**Comment by bparees** [comment]
may fix is this way instead: https://github.com/openshift/origin/pull/16083 for now.

**Comment by gabemontero** [comment]
deleting / updating comments in prep to avoid "flake req" on next attempt

**Comment by bparees** [comment]
ok, *this* will be the PR that should fix it: https://github.com/openshift/origin/pull/16085

**Comment by bparees** [comment]
[merge]

**Comment by gabemontero** [comment]
16085 has merged 

trying [merge]

**Comment by stevekuznetsov** [comment]
Since you're running off of the build stage you need to wait for a new one to have been built

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by bparees** [comment]
hooray.  Thanks @stevekuznetsov

**Comment by stevekuznetsov** [comment]
:fire:

**Comment by gabemontero** [comment]
yes thanks @stevekuznetsov !!

**Pull request merged**
